name: Check for yarn updates

permissions: {}

on:
  schedule:
    - cron: '0 5 1 * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/yarn_update.yml'
  workflow_dispatch:

jobs:
  yarn-update-check:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Update yarn
        uses: ffflorian/actions/yarn-update@f06ed1e06d898a98e4a130ba534c12d44bda9ded
        with:
          git_authorship: 'Florian Imdahl <git@ffflorian.de>'
